name: Submodules

on:
        push:
                branches: [ workflow-test ]

jobs:
        sync:
                runs-on: ubuntu-latest
                steps:
                        - name: Checkout
                          uses: actions/checkout@v2
                        - name: Sync
                          uses: srt32/git-actions@v0.0.3
                          with:
                                  args: 'git submodule sync && git submodule update --init'
